import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Main from '../components/Main'


export default function Home() {
  return (
    <div className='bg-zinc-800'>
        <div className='h-screen'>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Main/>


      
      </div>
      
      <Footer/>


      
    </div>
  )
}
